AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM template for DynamoDB CDC latency test

Parameters:
  DynamoDBStreamArn:
    Type: String
    Description: The ARN of the DynamoDB stream.

Resources:
  DynamoDBStreamProcessor:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: dynamo-cdc-latency-test
      Handler: app.lambda_handler
      Runtime: python3.9
      CodeUri: .
      Policies:
        - AWSLambdaBasicExecutionRole # Policy for CloudWatch Logs
        - DynamoDBCrudPolicy:
            TableName: FOS_DocStore_Compare_POC-dev-dynamodb
        - Statement:
          - Effect: Allow
            Action:
              - dynamodb:GetShardIterator
              - dynamodb:GetRecords
              - dynamodb:DescribeStream
              - dynamodb:ListStreams
            Resource: !Ref DynamoDBStreamArn
      Events:
        Stream:
          Type: DynamoDB
          Properties:
            Stream: !Ref DynamoDBStreamArn
            StartingPosition: LATEST
            BatchSize: 1
